// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIji4BsuSSjz3XNwc256U5R8cREVFtgAU',
    appId: '1:324971422370:web:a3c69f79f06af7ae776dfb',
    messagingSenderId: '324971422370',
    projectId: 'zenzone-72ceb',
    authDomain: 'zenzone-72ceb.firebaseapp.com',
    storageBucket: 'zenzone-72ceb.appspot.com',
    measurementId: 'G-D5XNT3NNZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7jER8GODJ2OD7mC8tD86NKNTJcYaBJfs',
    appId: '1:324971422370:android:c9e1bd840e2263ca776dfb',
    messagingSenderId: '324971422370',
    projectId: 'zenzone-72ceb',
    storageBucket: 'zenzone-72ceb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALTirUh0wimAQgm919Gn-UQegagBe0B6U',
    appId: '1:324971422370:ios:eff0eb3cf8d7a89c776dfb',
    messagingSenderId: '324971422370',
    projectId: 'zenzone-72ceb',
    storageBucket: 'zenzone-72ceb.appspot.com',
    iosClientId: '324971422370-pfe5v3nebe8q9iupjmk16rocb3hkpu67.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALTirUh0wimAQgm919Gn-UQegagBe0B6U',
    appId: '1:324971422370:ios:eff0eb3cf8d7a89c776dfb',
    messagingSenderId: '324971422370',
    projectId: 'zenzone-72ceb',
    storageBucket: 'zenzone-72ceb.appspot.com',
    iosClientId: '324971422370-pfe5v3nebe8q9iupjmk16rocb3hkpu67.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenzone',
  );
}
